hillandgertner/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import serve
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='index.html')),
    url(r'^front/', include('hillandgertner.pages.urls')),
]


urlpatterns += [
    url(r'^media/(?P<path>.*)$', serve, { 'document_root':settings.MEDIA_ROOT, 'show_indexes': True}),
    # url(r'^static/(?P<path>.*)$', serve, { 'document_root':settings.STATIC_ROOT, 'show_indexes': True})
]

hillandgertner/protected_pages/models.py
from __future__ import unicode_literals
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db import models
from tinymce.models import HTMLField
from hillandgertner.pages.models import Page
import subprocess
from django.conf import settings
# Create your models here.
from django.template.defaultfilters import slugify
# Create your models here.


PAGE_TYPES = (
    ('pdf', 'PDF File'),
    ('gallery', 'Gallery'),
)

class PDFManager(models.Manager):
    def get_queryset(self):
        return super(PDFManager, self).get_queryset().filter(
            type='pdf').order_by('order')

class GalleryManager(models.Manager):
    def get_queryset(self):
        return super(GalleryManager, self).get_queryset().filter(
            type='gallery').order_by('order')

class Image(models.Model):
    image = models.ImageField(blank=True, null=True)
    gallery = models.ForeignKey('ImageGallery', blank=True, null=True)
    order = models.IntegerField(default=0)

    class Meta:
        ordering = ("order",)



class ProtectedPage(models.Model):
    type = models.CharField(max_length=7, choices=PAGE_TYPES)
    date = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    parent_page = models.ForeignKey(Page, null=True, blank=True)
    background_image = models.ImageField(blank=True, null=True)
    heading = models.CharField(max_length=500, blank=False, null=True)
    subheading = models.CharField(max_length=500, blank=True, null=True)
    paragraph = HTMLField(blank=True, null=True)
    slug = models.SlugField(blank=True, null=True)
    order = models.IntegerField(default=0)
    pdf = models.FileField(blank=True, null=True)

    def __unicode__(self):
        return self.heading or self.date

    def get_url(self):
        return "#%s" % self.slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.heading)
        super(ProtectedPage, self).save(*args, **kwargs)

class PDFpage(ProtectedPage):
    def __init__(self, *args, **kwargs):
        self._meta.get_field('type').default = 'pdf'
        super(PDFpage, self).__init__(*args, **kwargs)
    objects = PDFManager()
    class Meta:
        proxy = True
        ordering = ("order",)
        verbose_name = "PDF page"
        verbose_name_plural = "PDF pages"

class ImageGallery(ProtectedPage):
    def __init__(self, *args, **kwargs):
        self._meta.get_field('type').default = 'gallery'
        super(ImageGallery, self).__init__(*args, **kwargs)
    objects = GalleryManager()
    class Meta:
        proxy = True
        ordering = ("order",)
        verbose_name = "Image gallery"
        verbose_name_plural = "Image galleries"



# method for updating
@receiver(post_save, sender=ProtectedPage, dispatch_uid="touch_tmp")
def touch_tmp(sender, instance, **kwargs):
     # print settings.BASE_DIR + "/tmp/restart.txt"
     subprocess.call(["touch", settings.BASE_DIR + "/tmp/restart.txt"])

hillandgertner/pages/templates/main.html
{% extends "base.html" %}
{% load secure_widgets utilities %}



{% block extra_CSS %}
    <style>
    .page-title{
    height:{{ globals.header_height }}vh;
    }
            .header-logo {
            height: {{ globals.header_height }}vh;
        }
            .page-content{
            top: {{ globals.header_height }}vh;

    }
            @media (min-width: 576px) {
                .page-content{

             margin-top: {{ globals.header_height }}vh;
    }
            }
    @media (max-width: 575px){
    .page-scroll{
          margin-top:-{{ header_height_adjusted }}vh;

    }
    }
    h1{
        font-size: {{ globals.heading_text_size }}px;
        color: {{ globals.heading_text_color }};
    }
    p{
        font-size: {{ globals.body_text_size }}px;
        color: {{ globals.body_text_color }};
    }
    .page-body p{
        font-size: {{ globals.body_text_size }}px;
        color: {{ globals.body_text_color }};
    }

    </style>
{% endblock %}


{% block content %}



    <div id="landing" class="landing" style="background-image:url(/media/landingpage-4.jpg);background-position:center;background-size:cover">
        <div class="container-fluid">
            <div class="row">
                <div class="landing-body">
{#                    <div class="landing-logo"><img class="logo" src="/media/img/Hill&Gertner-logo.svg"/></div>#}

                    <div class="landing-header">
                        <div class="landing-title"><h2 style="font-size:35px;  text-align: center;text-transform: capitalize;">Lorne Gertner</h2>
                            <hr />
                        <h3 style="border:none">Business Builder, Community Builder, City Builder.</h3>
                        </div>
                    </div>
                    <div class="landing-arrow"><img class="landing-down-arrow" src="/media/img/arrow-down.svg"/></div>
                </div>
            </div>
        </div>
    </div>
    <div id="trigger1"></div>

    <nav class="col-home-nav d-none d-sm-block sidebar padding-top-0">

        <div class="header-logo" style="background-image:url({{ logo }});">

                <a href="#"></a>

        </div>
        <ul class="nav nav-pills flex-column">

            <li class="nav-item">
                <button id="nav-toggle" class="hamburger hamburger--collapse is-active" type="button">
                          <span class="hamburger-box">
                            <span class="hamburger-inner"></span>
                          </span>
                </button>
                <div id="navigation" class="page-navigation">
                    <!--navigation goes here-->
                    <ul id="nav-drawer">
                        {% for page in pages %}
                            <li><a href="#{{ page.slug }}">{{ page.page_name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </li>

        </ul>

        <ul class="nav nav-pills flex-column down-arrow-container">
            <li class="nav-item">
                <img class="down-arrow" src="/media/img/arrow-down.svg"/>
            </li>

        </ul>


    </nav>

    <nav class="col-mobile-home-nav topbar padding-top-0">

        <ul class="nav flex-column mobile-header-logo">
            <li class="nav-item">
                <a class="nav-link" href="#"><img class="logo" src="{{ logo }}"/></a>
            </li>

        </ul>
        <ul class="nav nav-pills flex-column">

            <li class="nav-item">
                <button id="mobile-nav-toggle" class="hamburger hamburger--collapse" type="button">
                          <span class="hamburger-box">
                            <span class="hamburger-inner"></span>
                          </span>
                </button>
                <div id="mobile-navigation">
                    <!--navigation goes here-->
                    <ul id="mobile-nav-drawer">
                        {% for page in pages %}
                            <li><a href="#{{ page.slug }}">{{ page.page_name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </li>

        </ul>




    </nav>

    <div class="container-fluid full-page-title">
        <div class="row">
            <div id="page-header" class="col-12">
                <div class="page-title"><h1>{{ header_text }}</h1></div>
            </div>
        </div>
    </div>
    {% for page in pages %}
<style>
.{{ page.slug }} .page-body p{
        font-size: {{ page.body_text_size }}px;
        color: {{ page.body_text_color }};
    }
.{{ page.slug }} .page-body h2{
        font-size: {{ page.heading_text_size }}px;
        color: {{ page.heading_text_color }};
    }
.{{ page.slug }} .page-body h3{
        font-size: {{ page.subheading_text_size }}px;
        color: {{ page.subheading_text_color }};
    }
object{
    width:100%;
    height:100vh;
}
</style>
        <div class="page {{ page.slug }} section">

            <div class="container-fluid">
            <div class="row">
            <div class="col-12  page-title mobile-page-title"><h1>{{ header_text }}</h1></div>
            </div>
                <div class="row">

                    <a id="{{ page.slug }}" class="page-scroll"></a>
                    <main role="main" class="page-content full-page-content "
                          style='background-image:url("{% if page.background_image %}{{ page.background_image.url }}{% endif %}");'>




                        <div class="page-body col-md-{% if page.num_columns %}{{ page.num_columns }}{% else %}12{% endif %} col-lg-{% if page.num_columns %}{{ page.num_columns }}{% else %}12{% endif %} col-sm-12" >
                            <section class="{% if page.text_format %}{{ page.text_format }}{% endif %} placeholders">


                                    {% autoescape off %}{{ page.copy }}{% endautoescape %}


                            </section>


                        </div>
                                {% if user.is_authenticated %}
                                {% for protected_page in page.protectedpage_set.all|cleanup_pages|dictsort:"order" %}
                                {% if protected_page.heading %}
                                    <div class="row">
                                    <div class="page-body col-md-12 col-lg-12 col-sm-12 {{ protected_page.type }}" >
                                    <section class=" placeholders">

                                    {% if protected_page.type == "pdf" %}
                                        <object data="{% if protected_page.pdf %}{{ protected_page.pdf.url }}{% endif %}" type="application/pdf" >
                                            alt : <a href="{% if protected_page.pdf %}{{ protected_page.pdf.url }}{% endif %}">{{ protected_page.page_name }}</a>
                                        </object>
                                    {% elif protected_page.type == "gallery" %}
                                        {% image_gallery protected_page %}
                                    {% endif %}

                                    </section>
                                    </div>
                                    </div>
                                    <hr />
                                    {% endif %}
                                {% endfor %}
                                {% else %}
                                    {% if page.protectedpage_set.all|cleanup_pages %}

                                    <div class="page-body col-md-12 col-lg-12 col-sm-12" >
                                    <section class=" placeholders">
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-page-id="{{ page.slug }}" data-target="#loginModal">
  LOGIN
</button>
                                    </section>
                                    </div>

                    {% endif %}
                    {% endif %}


                    </main>
                </div>
            </div>
        </div>

    {% endfor %}


{% endblock %}

hillandgertner/pages/templates/main.static.html
{% extends "base.html" %}
{% block content %}

<div class="landing">
    <div class="container-fluid">
        <div class="row">
            <div class="landing-body">
                <div class="landing-logo"><img class="logo" src="/media/img/Hill&Gertner-logo.svg" /></div>
                <div class="landing-arrow"><img class="landing-down-arrow" src="/media/img/arrow-down.svg" /></div>
                <div class="landing-header">
                    <div class="landing-title"><h3>a talent-based merchant bank</h3></div>
                </div>
            </div>
        </div>
    </div>
</div>


<nav class="col-home-nav d-none d-sm-block sidebar padding-top-0">

    <ul class="nav flex-column header-logo">
        <li class="nav-item">
            <a class="nav-link" href="#"><img class="logo" src="/media/img/Hill&Gertner-logo.svg" /></a>
        </li>

    </ul>
    <ul class="nav nav-pills flex-column">

        <li class="nav-item">
            <button id="nav-toggle" class="hamburger hamburger--collapse" type="button">
                          <span class="hamburger-box">
                            <span class="hamburger-inner"></span>
                          </span>
            </button>
            <div id="navigation">
                <!--navigation goes here-->
                <ul id="nav-drawer">
                    <li><a href="#home">company</a></li>
                    <li><a href="#services">services</a></li>
                    <li><a href="#gertner">lorne gertner</a></li>
                    <li><a href="#brands">brands</a></li>

                </ul>
            </div>
        </li>

    </ul>

    <ul class="nav nav-pills flex-column down-arrow-container">
        <li class="nav-item">
            <img class="down-arrow" src="/media/img/arrow-down.svg" />
        </li>

    </ul>


</nav>
<div id="home" class="home section">
    <!--<a name="home"></a>-->
    <div class="container-fluid">
        <div class="row">


            <main role="main" class="col-sm-9 ml-sm-auto col-md-10 pt-3">
                <div class="page-title"><h1>a talent-based merchant bank</h1></div>
                <div class="page-body">
                <section class="row text-justify placeholders">
                    <div class="col-11 placeholder">
                        <p><strong>Hill & Gertner</strong> Capital Corporation (Hill & Gertner) is a talent-based merchant bank headquartered in Toronto. We invest our own
                            capital and that of third parties, and form partnerships with proven creative entrepreneurs who have extensive expertise in their
                            respective fields. We are an agile organization driven by our belief in the entrepreneurial spirit, our ability to recognize new opportunities,
                            and our long-standing personal relationships across all industries.</p>

                            <p>At Hill & Gertner, we embrace change and disruption, believing that it is a natural by-product of progress. When we see change, we
                            see opportunity. More than this, we have the knowledge, know-how and financial resources to capitalize on the ever-evolving business
                            environment. We work with retailers, manufacturers, distributors and service providers whose businesses are being affected by
                            expansion, re-tooling, a business climate in flux, and mergers or acquisitions. Moreover, we are not intimidated by financial distress.
                            Our strength is in our ability to act quickly and deploy our expertise and capital to maximum effect.</p>
                    </div>

                </section>



                </div>
            </main>
        </div>
    </div>
</div>


<div id="services" class="services section">
    <!--<a name="services"></a>-->
    <div class="container-fluid">
        <div class="row">


            <main role="main" class="col-sm-9 ml-sm-auto col-md-10 pt-3">
                <div class="page-title"><h1>a talent-based merchant bank</h1></div>
                <div class="page-body">
                    <section class="row text-justify placeholders">
                        <div class="col-11 placeholder">
                            <h2>Hill & Gertner Retail Partners (HGRP)</h2>
                            <p><strong>Hill & Gernter Retail Partners (HGRP)</strong> is an investment banking and advisory firm specializing in the merchandising sector, including
                                retail and consumer goods. HGRP are also principals and equity investors in successful retail and consumer product companies.
                                HGRP’s services include branding and rebranding mergers and acquisitions, capital solutions, consolidations, restructuring, real estate
                                solutions, and advisory services.</p>

                            <p>HGRP’s expertise in branding, merchandising, consolidations, restructuring and banking means that it understands a company’s potential
                                and can maximize that value in any kind of transaction. More than any other company in Canada, HGRP knows what it takes to be a
                                successful retailer. Since 1996, HGRP has been involved in retail consumer product transactions totaling well over $1 billion.</p>

                            <p>HGRP’s principals have visionary, branding, strategic, merchandising and operational skills that are unmatched in the Canadian market.
                                These skills are complemented by an expertise in financial engineering, all of which enables HGRP to provide creative turnkey solutions.</p>

                            <hr />

                            <h2>Quadrangle Architects Limited</h2>
                            <p>
                                Since its formation in 1986, Quadrangle Architects Limited has established itself as one of Canada’s most dynamic architectural firms.
                                The practice was formed by the merger of Klein Taylor Goldsmith Limited (established in 1978) and Curtner Brown Architects
                                (established in 1981).</p>

                                <p>Wide-ranging in its scope and abilities, Quadrangle has assembled a portfolio of projects that illustrates a diverse client list and expertise
                                in a wide variety of building types from corporate to commercial to residential. In addition to its many large-scale projects, Quadrangle is
                                highly regarded for its corporate and commercial interiors carried out by its in-house interior design group.

                            </p>



                        </div>

                    </section>



                </div>
            </main>
        </div>
    </div>
</div>


<div id="gertner" class="gertner section">

    <div class="header-back"></div>
    <div class="container-fluid">
        <div class="row">


            <main role="main" class="col-sm-9 ml-sm-auto col-md-10 pt-3">
                <div class="page-title"><h1>a talent-based merchant bank</h1></div>
                <div class="page-body">
                    <section class="row placeholders">
                        <div class="col-6 placeholder">
                            <h2>LORNE GERTNER</h2>
                            <p>Mr. Gertner is a serial entrepreneur with experience in start-ups, going public
                                transactions, fashion, retail, architecture, real estate, finance and cannabis.
                                Mr. Gertner is a co-founder and former chairman of PharmaCan Capital
                                Corporation (MMJ.V) (now Cronos) Canada’s first publicly traded merchant
                                bank in the medical marijuana sector with investments in five of the thirty-eight
                                legal licensed producers in Canada. He is also a cofounder of Tokyo Smoke.
                                Mr. Gertner was a cofounder and director of Cannasat Pharmaceuticals Inc.
                                (CYNA) The first medical marijuana company to be listed on the Toronto stock
                                exchange with an investment in the first government contracted facility growing
                                medical marijuana in Canada called Prairie Plant Systems now called
                                Cannimed Therapeutics Inc. (CMED.TO).</p>

                            <p>Mr. Gertner is the current Chairman of HG2 Capital Corp., an investment /
                                merchant bank in the cannabis sector, and is the CEO of Hill and Gertner Capital
                                Corp.  He concurrently serves on the boards of Emblem Corp. (EMC.V), Green
                                Acre Capital and the Design Exchange. He is also an advance professor at the
                                Daniel School of Architecture Landscape and Urban Design at The University of
                                Toronto.</p>

                            <p>Mr. Gertner is a graduate of The John H. Daniels Faculty of Architecture, University
                                of Toronto and has completed the ICD.D designation at the Rotman School of
                                Management. </p>
                        </div>

                    </section>



                </div>
            </main>
        </div>
    </div>
</div>


<div id="brands" class="brands section">

    <div class="container-fluid">
        <div class="row">


            <main role="main" class="col-sm-9 ml-sm-auto col-md-10 pt-3">
                <div class="page-title"><h1>a talent-based merchant bank</h1></div>
                <div class="page-body">
                    <section class="row text-justify placeholders">
                        <div class="col-11 placeholder">
                            <h2>Cynapsus</h2>
                            <p>Cynapsus is a specialty pharmaceutical company developing a convenient and easy to use sublingual (oral) thin film strip for the acute
                                rescue of “off” motor symptoms of Parkinson’s disease. Over one million people in the U.S. and an estimated 5 million people globally
                                suffer from Parkinson's disease. Parkinson’s disease is a chronic and progressive neurodegenerative disease that impacts motor activity,
                                and its prevalence is increasing with the aging of the population.
                            </p>

                            <h2>Tokyo Smoke</h2>
                            <p>
                                <img class="peacock-image" src="/media/img/peacock-parade.png" />Tokyo Smoke is for the sophisticated smoker, those who embrace beautiful design along with alternative states of
                                mind. They believe a smoke session should be approached with the same thoughtful consideration as preparing a
                                perfect cup of coffee. It’s for active days and chill nights—or chill days and active nights. It’s a culture that believes in
                                the experience: a well-curated smoke session, one of intention or imagination, is always worth the trip.</p>

                            <p>Tokyo Smoke is a leading Canadian lifestyle brand, the first to elevate a new, burgeoning industry. Driven by design,
                                Tokyo Smoke is ushering in a new era with high end coffee, an elevated retail experience and its signature collection
                                of smoking accessories. </p>

                            <h2>The Peacock Parade</h2>

                            <p>The Peacock Parade is the discerning shoppers’ answer to elite e-commerce. Their merchandise curators provide members with a refined
                                collection of affordable luxury, presented amidst flawless aesthetic. By imposing the highest standards of selection, they maintain the
                                integrity of their brands. Members experience the elegance of couture, the adrenaline of a sample sale and the sophistication of service
                                traditionally reserved for the privileged.</p>

                            <p><a href="http://www.thepeacockparade.com" target="_blank">www.thepeacockparade.com</a></p>

                        </div>

                    </section>



                </div>
            </main>
        </div>
    </div>
</div>

{% endblock %}