hillandgertner/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import serve
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='index.html')),
    url(r'^front/', include('hillandgertner.pages.urls')),
]


urlpatterns += [
    url(r'^media/(?P<path>.*)$', serve, { 'document_root':settings.MEDIA_ROOT, 'show_indexes': True}),
    # url(r'^static/(?P<path>.*)$', serve, { 'document_root':settings.STATIC_ROOT, 'show_indexes': True})
]

hillandgertner/protected_pages/models.py
from __future__ import unicode_literals
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db import models
from tinymce.models import HTMLField
from hillandgertner.pages.models import Page
import subprocess
from django.conf import settings
# Create your models here.
from django.template.defaultfilters import slugify
# Create your models here.


PAGE_TYPES = (
    ('pdf', 'PDF File'),
    ('gallery', 'Gallery'),
)

class PDFManager(models.Manager):
    def get_queryset(self):
        return super(PDFManager, self).get_queryset().filter(
            type='pdf').order_by('order')

class GalleryManager(models.Manager):
    def get_queryset(self):
        return super(GalleryManager, self).get_queryset().filter(
            type='gallery').order_by('order')

class Image(models.Model):
    image = models.ImageField(blank=True, null=True)
    gallery = models.ForeignKey('ImageGallery', blank=True, null=True)
    order = models.IntegerField(default=0)

    class Meta:
        ordering = ("order",)



class ProtectedPage(models.Model):
    type = models.CharField(max_length=7, choices=PAGE_TYPES)
    date = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    parent_page = models.ForeignKey(Page, null=True, blank=True)
    background_image = models.ImageField(blank=True, null=True)
    heading = models.CharField(max_length=500, blank=False, null=True)
    subheading = models.CharField(max_length=500, blank=True, null=True)
    paragraph = HTMLField(blank=True, null=True)
    slug = models.SlugField(blank=True, null=True)
    order = models.IntegerField(default=0)
    pdf = models.FileField(blank=True, null=True)

    def __unicode__(self):
        return self.heading or self.date

    def get_url(self):
        return "#%s" % self.slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.heading)
        super(ProtectedPage, self).save(*args, **kwargs)

class PDFpage(ProtectedPage):
    def __init__(self, *args, **kwargs):
        self._meta.get_field('type').default = 'pdf'
        super(PDFpage, self).__init__(*args, **kwargs)
    objects = PDFManager()
    class Meta:
        proxy = True
        ordering = ("order",)
        verbose_name = "PDF page"
        verbose_name_plural = "PDF pages"

class ImageGallery(ProtectedPage):
    def __init__(self, *args, **kwargs):
        self._meta.get_field('type').default = 'gallery'
        super(ImageGallery, self).__init__(*args, **kwargs)
    objects = GalleryManager()
    class Meta:
        proxy = True
        ordering = ("order",)
        verbose_name = "Image gallery"
        verbose_name_plural = "Image galleries"



# method for updating
@receiver(post_save, sender=ProtectedPage, dispatch_uid="touch_tmp")
def touch_tmp(sender, instance, **kwargs):
     # print settings.BASE_DIR + "/tmp/restart.txt"
     subprocess.call(["touch", settings.BASE_DIR + "/tmp/restart.txt"])

hillandgertner/pages/templates/tags/carousel.html
{#<div id="{{ protected_page.slug }}" style="height:75vh" class="carousel slide secured-widget" data-ride="carousel">#}
{#  <ol class="carousel-indicators">#}
{#      {% for image_item in protected_page.image_set.all %}#}
{#    <li data-target="#{{ protected_page.slug }}" data-slide-to="{{ forloop.counter0 }}" class="{% if forloop.first %}active{% endif %}"></li>#}
{#    {% endfor %}#}
{#  </ol>#}
{#  <div class="carousel-inner">#}
{#      {% for image_item in protected_page.image_set.all %}#}
{#    <div class="carousel-item {% if forloop.first %}active{% endif %}">#}
{#      <img class="d-block w-100" src="{{ image_item.image.url }}" alt="{{ image_item.image }}">#}
{#    </div>#}
{#      {% endfor %}#}
{#  </div>#}
{#  <a class="carousel-control-prev" href="#{{ protected_page.slug }}" role="button" data-slide="prev">#}
{#    <span class="carousel-control-prev-icon" aria-hidden="true"></span>#}
{#    <span class="sr-only">Previous</span>#}
{#  </a>#}
{#  <a class="carousel-control-next" href="#{{ protected_page.slug }}" role="button" data-slide="next">#}
{#    <span class="carousel-control-next-icon" aria-hidden="true"></span>#}
{#    <span class="sr-only">Next</span>#}
{#  </a>#}
{#</div>#}





<div class="container gallery-container">

    <h1 class="text-center" style="font-size:24px">{{ protected_page.heading }}</h1>
    {% if protected_page.subheading %}<h3 class="text-center" style="color:#6b6a6a;padding-right:24px;">{{ protected_page.subheading }}</h3>{% endif %}

    <div style="padding-right:24px;color:#000">{% autoescape off %}{{ protected_page.paragraph }}{% endautoescape %}</div>

    <div class="tz-gallery">

        <div class="row">
{% for image_item in protected_page.image_set.all %}
    {% if image_item.image %}
            <div class="{% if forloop.counter|divisibleby:3 %}col-sm-6 col-md-3{% elif forloop.counter|divisibleby:2 or forloop.counter|divisibleby:3 %}col-sm-12 col-md-6{% else %}col-sm-6 col-md-3{% endif %} gallery-image" style="background-image:url('{{ image_item.image.url }}');">
                <a class="lightbox" href="{{ image_item.image.url }}">
                    <img src="{{ image_item.image.url }}" alt="{{ image_item.image }}">
                </a>
            </div>
    {% endif %}
{% endfor %}


        </div>

    </div>

</div>